export const FETCHING_PROJECTS = 'FETCHING_PROJECTS';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_FAILURE = 'FETCH_PROJECTS_FAILURE';

export const FETCHING_PROJECT = 'FETCHING_PROJECT';
export const FETCH_PROJECT_SUCCESS = 'FETCH_PROJECT_SUCCESS';
export const FETCH_PROJECT_FAILURE = 'FETCH_PROJECT_FAILURE';

export const FETCHING_TICKETS_BY_PROJECT = 'FETCHING_TICKETS_BY_PROJECT';
export const FETCH_TICKETS_BY_PROJECT_SUCCESS = 'FETCH_TICKETS_BY_PROJECT_SUCCESS';
export const FETCH_TICKETS_BY_PROJECT_FAILURE = 'FETCH_TICKETS_BY_PROJECT_FAILURE';

export const FETCHING_STATUSES = 'FETCHING_STATUSES';
export const FETCH_STATUSES_SUCCESS = 'FETCH_STATUSES_SUCCESS';
export const FETCH_STATUSES_FAILURE = 'FETCH_STATUSES_FAILURE';

export const DELETING_TICKET = 'DELETING_TICKET';
export const DELETE_TICKET_SUCCESS = 'DELETE_TICKET_SUCCESS';
export const DELETE_TICKET_FAILURE = 'DELETE_TICKET_FAILURE';
