export const FETCHING_PROJECTS = 'FETCHING_PROJECTS';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_FAILURE = 'FETCH_PROJECTS_FAILURE';

export const FETCHING_TICKETS_BY_PROJECT = 'FETCHING_TICKETS_BY_PROJECT';
export const FETCH_TICKETS_BY_PROJECT_SUCCESS = 'FETCH_TICKETS_BY_PROJECT_SUCCESS';
export const FETCH_TICKETS_BY_PROJECT_FAILURE = 'FETCH_TICKETS_BY_PROJECT_FAILURE';
